tasks/urls.py
# -*- coding:utf-8 -*-
# coding=<utf8>

# from django.conf.urls.defaults import patterns, include, url
from django.conf.urls import url, include
# from django.conf.urls import patterns, url, include
# from django.conf.urls.defaults import *

import todoes.views
import todoes.api
import assets.views
import save_state.api
import snmp.api
import assets.test_view
import assets.api
import logs.views
import user_settings.views
import djlib
from django.contrib import admin
from django.contrib.auth.views import login, logout, \
    password_change, password_change_done
from django.conf import settings

admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# example from tutorial for 1.10
# urlpatterns = [
#     url('^$', views.myview),
#     url('^other/$', views.otherview),
# ]
# urlpatterns = patterns('',
urlpatterns = [
    # просмотр задач
    url(r'^tasks/$', todoes.views.tasks),
    # просмотр всех задач по страницам
    url(r'^all_task/([^/]+)/$', todoes.views.all_tasks),
    # просмотр сообщения
    url(r'^messages/show/(\d+)/$',
        todoes.views.messages_show_message),

    # обычные задачи
    url(r'^new_ticket/$', todoes.views.new_ticket),
    url(r'^edit/([^/]+)/$', todoes.views.edit_task),
    # подвтерждение срока переноса задачи
    url(r'^task_accept_request_due_date/(\d+)/$',
        todoes.views.accept_request_due_date),
    # отклонение срока переноса задачи
    url(r'^task_reject_request_due_date/(\d+)/$',
        todoes.views.reject_request_due_date),
    # закрытие / отмена закрытия заявки
    url(r'^close/([^/]+)/$', todoes.views.close_task),
    url(r'^unclose/([^/]+)/$', todoes.views.unclose_task),
    # подтверждение выполнения задачи
    url(r'^confirm/([^/]+)/$', todoes.views.confirm_task),
    # повторяющиеся задачи
    # создание повторяющейся задачи
    url(r'^new_regular_ticket/$', todoes.views.new_regular_ticket),
    # редактирование повторяющейся задачи
    url(r'^edit_regular/([^/]+)/$', todoes.views.edit_regular_task),
    # отметка как сделанная повторяющейся задачи
    url(r'^regular_task_done/([^/]+)/$',
        todoes.views.regular_task_done),
    # общее для всех задач
    url(r'^task/([^/]+)/(\d+)/$', todoes.views.task),
    # установка напоминалки повторяющейся задачи
    # удаление повторяющейся задачи
    url(r'^deleted_tasks/$', todoes.views.deleted_tasks),
    url(r'^delete/([^/]+)/(\d+)/$', todoes.views.delete_task),
    url(r'^completle_delete/([^/]+)/(\d+)/$',
        todoes.views.completle_delete_task),
    url(r'^undelete/([^/]+)/(\d+)/$', todoes.views.undelete_task),
    url(r'^add_children_task/([^/]+)/(\d+)/$',
        todoes.views.add_children_task),
    # http://192.168.1.157:8080/move_to_call/47
    # изменение категории на "Звонки"
    url(r'^move_to_call/([^/]+)/(\d+)/$', todoes.views.move_to_call),
    # http://192.168.1.157:8080/set_reminder/47
    # установка напоминания для задачи
    url(r'^set_reminder/([^/]+)/(\d+)/$', todoes.views.set_reminder),
    # Для администратора:
    url(r'^users/$', todoes.views.get_all_logged_in_users),
    url(r'^users/activity_history/([^/]+)/([^/]*)/$',
        todoes.views.get_user_activity_history),
    url(r'^tasks/to/([^/]+)/$', todoes.views.to),
    # добавление сообщения
    url(r'^messages/add/$', todoes.views.messages_add),
    # API для задач
    # Получение человеческого представления hardcore-style при
    # создании регулярной задачи
    url(r'^api/crontab_to_russian/([^/]+)/$',
        todoes.api.crontab_to_human),

    url(r'^accounts/$', login),
    url(r'^login/$', login),
    url(r'^accounts/login/$', login),
    url(r'^test/password2/$', password_change),
    url(r'^password_change_done/$', password_change_done),
    url(r'^accounts/register/$', todoes.views.register),
    url(r'^accounts/logout/$', logout),
    url(r'^accounts/profile/$', todoes.views.profile),
    # Uncomment the admin/doc line below to enable admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', todoes.views.tasks),

    # изменение языка интерфейса
    url(r'^language/([^/]+)/$',
        djlib.multilanguage_utils.change_language),

    # Работа с активами
    # Добавление чека, где указывается плата + сколько там чего
    url(r'^bill/cash/add/$', assets.views.bill_cash_add),
    # Добавление счёта, где указывается плата + сколько там чего
    url(r'^bill/cashless/add/$', assets.views.bill_cashless_add),
    # Просмотр списка счетов, как по налу так и по безналу с фильтрами
    url(r'^all_bills/$', assets.views.all_bills),
    # Просмотр конкретного чека/счёта - тип,id
    url(r'^bill/show/([^/]+)/(\d*)/$', assets.views.show_bill),
    # Список всех удалённых чеков/счётов
    url(r'^all_deleted_bills/$', assets.views.all_deleted_bills),
    # Просмотр активов по категориям
    url(r'^assets_by_type/(\d*)/$', assets.views.assets_by_type),
    # Просмотр актива
    url(r'^asset/(\d*)/$', assets.views.asset_view),

    # API для работы с активами
    # Выдача формы добавления актива, в качестве параметра
    # категория актива, префикс к имени полей формы (число)
    url(r'^api/get_asset_add_form/(\d+)/(\d*)/$',
        assets.api.get_asset_add_form),
    # Выдача заголовка для формы добавления актива
    url(r'^api/get_asset_add_form_header/$',
        assets.api.get_asset_add_form_header),
    # Выдача скрипта для формы добавления актива
    url(r'^api/get_asset_add_form_script/(\d+)/(\d*)/$',
        assets.api.get_asset_add_form_script),
    # Выдача списка поставщиков, в качестве параметра -
    # тот поставщик, который должен быть указан, name
    url(r'^api/get_contractors_list/([^/]*)/$',
        assets.api.get_contractors_list),
    # Выдача формы добавления поставщика, в качестве параметра -
    # название
    url(r'^api/get_new_contractor_add_form/([^/]*)/$',
        assets.api.get_new_contractor_add_form),
    # Сохраняем нового поставщика
    url(r'^api/save_new_contractor/$',
        assets.api.save_new_contractor),
    # Получаем список типов активов, в качестве парамета -
    # id выбранного
    url(r'^api/get_asset_type_list/(\d*)/$',
        assets.api.get_asset_type_list),
    # Пометить конкретный чек/счёт к удалению - тип,id
    url(r'^api/bill/delete/([^/]+)/(\d*)/$',
        assets.api.mark_as_deleted_bill),
    url(r'^bill/delete/([^/]+)/(\d*)/$',
        assets.api.mark_as_deleted_bill),
    # Удалить конкретный чек/счёт - тип,id
    url(r'^api/bill/full_delete/([^/]+)/(\d*)/$',
        assets.api.full_delete_bill),
    url(r'^bill/full_delete/([^/]+)/(\d*)/$',
        assets.api.full_delete_bill),
    # Получение списка активов по категориям
    url(r'^api/assets_by_type/(\d+)/$', assets.api.assets_by_type),
    # Удаление актива - id актива, id категории к которой вернуться
    # при ошибки
    url(r'^api/asset/delete/(\d+)/(\d+)/$', assets.api.asset_delete),
    # Редактирование актива - id актива
    url(r'^api/asset/edit/(\d+)/$', assets.api.asset_edit),
    # получение json списка моделей для типа активов- тип актива
    url(r'^api/asset_types/models/get/(\d+)/$',
        assets.api.get_models_list_json),
    # Получение формы для добавления нового типа актива
    url(r'^api/asset_types/type/add/$',
        assets.api.get_new_asset_type_add_form),
    # Сохраняем новый тип актива
    url(r'^api/asset_types/type/save/$',
        assets.api.get_new_asset_type_save),
    # Редактирование актива - id актива
    url(r'^api/asset/save_edited/(\d+)/$',
        assets.api.asset_save_edited),
    # Получаем форму для добавления актива - id типа актива,
    # имя модели
    url(r'^api/get_new_model_add_form/(\d+)/(.+)/$',
        assets.api.get_new_asset_model_add_form),
    # Сохраняем новую модель актива- id типа актива
    url(r'^api/asset_types/model/save/(\d+)/$',
        assets.api.save_new_model),
    # Меняем пройденные этапы для счёта по безналу - номер счёта,
    # название этапа, включить/выключить (провести/отменить
    # проведение), послать таблицу или перенаправить страницу?
    url(r'^api/bill/cashless/edit/stages/(\d+)/([^/]+)/(\d+)/(\d+)$',
        assets.api.cashless_edit_stages),
    # API для выдачи JSON
    # Список моделей актива для типа актива - id типа актива
    url(r'^api/json/get/models/(\d+)/$', assets.api.json_models),
    # Получение цены и срока гарантии для последнего купленного
    #  актива этой модели этой фирмы. Данные передаются через
    #  POST запрос
    url(r'^api/json/get/price_and_warranty/$',
        assets.api.json_price_and_warranty),
    # Логирование и т.п.
    url(r'^show_last_logs/(\d*)/$', logs.views.show_last_logs),
    # API для сохранения статусов
    # сохранение статуса через http
    url(
        r'^api/state/save_by_http/'
        r'([^/]+)/([^/]+)/([^/]+)/(\d+)/([^/]*)/(\d+)/([^/]+)/$',
        save_state.api.save_by_http),
    # просмотр статусов
    url(r'^api/state/show_states/([^/]+)/$',
        save_state.api.show_states),
    # API snmp
    # просмотр карты сети
    url(r'^api/snmp/show_network_map/$',
        snmp.api.show_network_map),
    # просмотр карты роутера по community string & ip
    url(r'^api/snmp/show_router_mapping/([^/]+)/(\d+.\d+.\d+.\d+)/$',
        snmp.api.show_router_mapping),
    # просмотр карты по номеру роутера в базе
    url(r'^api/snmp/show_router_mapping_by_id/(\d+)/$',
        snmp.api.show_router_mapping_by_id),
    # определение производителя по маку
    url(
        r'^api/snmp/brand_by_mac/'
        r'([0-9a-fA-F]{6})/$',
        snmp.api.brand_by_mac),
    # определение имени по ip
    url(r'^api/snmp/name_by_ip/(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})/$',
        snmp.api.name_by_ip),
    # определение имени по ip
    url(
        r'^api/snmp/find_by_mac/'
        r'([0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:'
        r'[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2})/$',

todoes/forms.py
# -*- coding:utf-8 -*-
# coding=<utf8>

#TODO: сделать английские формы

from django import forms
from todoes.models import Note, Resource, File, Person, Task, ProblemByWorker, ProblemByUser, Categories
# from tasks.todoes.models import Worker, Client
from django.contrib.auth.forms import UserCreationForm
from django.contrib.admin import widgets

RUS_PRIORITY_CHOICES = (
        ('1','Лазар/Борода/Мотя'),
        ('2','Если не сделать сейчас - огребём проблем потом'),
        ('3','Всё остальное'),
        ('4','В ближайшем будущем'),
        ('5','Когда время будет')
    )
ENG_PRIORITY_CHOICES = (
        ('1','Lazar/Boroda/Motya'),
        ('2','Если не сделать сейчас - огребём проблем потом'),
        ('3','Всё остальное'),
        ('4','В ближайшем будущем'),
        ('5','Когда время будет')
    )
    
inp_f=( '%d-%m-%Y %H:%M:%S',     # '2006-10-25 14:30:59'
        '%d-%m-%Y %H:%M',        # '2006-10-25 14:30'
        '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30'
        '%d-%m-%Y',              # '2006-10-25'
        '%d/%m/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
        '%d/%m/%Y %H:%M',        # '10/25/2006 14:30'
        '%d/%m/%Y',              # '10/25/2006'
        '%d.%m.%Y %H:%M:%S',     # '10/25/2006 14:30:59'
        '%Y.%m.%d %H:%M:%S',     # '2010/01/26 14:30:59'
        '%d/%m/%y %H:%M:%S',     # '10/25/06 14:30:59'
        '%d/%m/%y %H:%M',        # '10/25/06 14:30'
        '%d/%m/%y',       )
class NewTicketForm(forms.Form):
    name = forms.CharField(max_length=140, label='Название заявки')
    pbus = forms.ModelChoiceField(queryset  = ProblemByUser.objects.all(), label='Проблема со слов пользователя')
    description = forms.CharField(widget=forms.Textarea, label='Описание')
    clients = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Заявитель')
    priority = forms.ChoiceField(widget=forms.RadioSelect,choices = PRIORITY_CHOICES, label='Приоритет')
    category = forms.ModelChoiceField(queryset  = Categories.objects.all(), label='Категория')
    start_date = forms.DateTimeField(label='Дата создания заявки')
    due_date = forms.DateTimeField(label='Предполагаемая дата завершения',input_formats=inp_f)
    workers = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Исполнитель')
    percentage = forms.DecimalField(min_value=0, max_value=100, label='Процент выполнения')
    
class TicketEditForm(forms.Form):
    name = forms.CharField(max_length=140, label='Название заявки')
    pbus = forms.ModelChoiceField(queryset  = ProblemByUser.objects.all(), label='Проблема со слов пользователя')
    description = forms.CharField(widget=forms.Textarea, label='Описание')
    clients = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Заявитель')
    priority = forms.ChoiceField(choices = PRIORITY_CHOICES, label='Приоритет')
    category = forms.ModelChoiceField(queryset  = Categories.objects.all(), label='Категория')
    start_date = forms.DateTimeField(label='Дата создания заявки',input_formats=inp_f)
    when_to_reminder = forms.DateTimeField(label='Установить напоминание',input_formats=inp_f,required=False)
    due_date = forms.DateTimeField(label='Предполагаемая дата завершения',input_formats=inp_f)
    workers = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Исполнитель')
    percentage = forms.DecimalField(min_value=0, max_value=100, label='Процент выполнения')
class NewRegularTicketForm(forms.Form):
    name = forms.CharField(max_length=140, label='Название заявки')
    description = forms.CharField(widget=forms.Textarea, label='Описание',required=False)
    clients = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Заявитель')
    priority = forms.ChoiceField(widget=forms.RadioSelect,choices = PRIORITY_CHOICES, label='Приоритет')
    category = forms.ModelChoiceField(queryset  = Categories.objects.all(), label='Категория')
    start_date = forms.DateTimeField(label='Дата создания заявки',input_formats=inp_f)
    stop_date = forms.DateTimeField(label='Дата завершения',input_formats=inp_f,required=False)
    workers = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Исполнитель')
class EditRegularTicketForm(forms.Form):
    name = forms.CharField(max_length=140, label='Название заявки')
    description = forms.CharField(widget=forms.Textarea, label='Описание',required=False)
    clients = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Заявитель')
    priority = forms.ChoiceField(widget=forms.RadioSelect,choices = PRIORITY_CHOICES, label='Приоритет')
    category = forms.ModelChoiceField(queryset  = Categories.objects.all(), label='Категория')
    start_date = forms.DateTimeField(label='Дата создания заявки',input_formats=inp_f)
    when_to_reminder = forms.DateTimeField(label='Установить напоминание',input_formats=inp_f,required=False)
    stop_date = forms.DateTimeField(label='Дата завершения',input_formats=inp_f,required=False)
    workers = forms.ModelChoiceField(queryset  = Person.objects.all(), label='Исполнитель')

class TicketClosingForm(forms.Form):
    done_date = forms.DateTimeField(label='Дата закрытия заявки',input_formats=inp_f)
    pbw = forms.ModelChoiceField(queryset  = ProblemByWorker.objects.all(), label='Выявленная проблема')
class TicketConfirmingForm(forms.Form):
    confirmed = forms.BooleanField(required=False)
    confirmed_date = forms.DateTimeField(label='Дата подтверждения закрытия заявки',input_formats=inp_f)
    
# class NoteToTicketAddForm(forms.Form):
    # note = forms.CharField(widget=forms.Textarea, label='Комментарий',required=False )
    # workers = forms.ModelMultipleChoiceField(queryset  = Person.objects.all(), label='Кого ещё уведомить о комментарии?',required=False)

    
class UserCreationFormMY(UserCreationForm):
    fio = forms.CharField(label='ФИО')
    mail = forms.EmailField(label = 'Мыло')
    tel = forms.CharField(label='Телефон', max_length=10, min_length=10)
    
class TicketSearchForm(forms.Form):
    name = forms.CharField(max_length=140, label='Текст для поиска')

class NoteToTicketAddForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.defaults = kwargs.pop('defaults','')
        self.exclude = kwargs.pop('exclude','')
        super(NoteToTicketAddForm, self).__init__(*args, **kwargs)
        self.fields['workers'].queryset = Person.objects.exclude(fio__in = [person.fio for person in self.exclude ])
        self.fields['workers'].initial = Person.objects.filter(fio__in = self.defaults)

    note = forms.CharField(widget=forms.Textarea, label='Комментарий',required=False )
    workers = forms.ModelMultipleChoiceField(queryset  = Person.objects.all(), label='Кого ещё уведомить о комментарии?',required=False,)
class File_and_NoteToTicketAddForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.defaults = kwargs.pop('defaults','')
        self.exclude = kwargs.pop('exclude','')
        super(File_and_NoteToTicketAddForm, self).__init__(*args, **kwargs)
        self.fields['workers'].queryset = Person.objects.exclude(fio__in = [person.fio for person in self.exclude ])
        self.fields['workers'].initial = Person.objects.filter(fio__in = self.defaults)

    note = forms.CharField(widget=forms.Textarea, label='Комментарий',required=False )
    file  = forms.FileField()
    workers = forms.ModelMultipleChoiceField(queryset  = Person.objects.all(), label='Кого ещё уведомить о комментарии?',required=False,)

todoes/templates/RUS/all_tasks.html
{% extends "RUS/base.html" %}
{% block title %}
    Архив тикетов
{% endblock %}
{% block style %}
    <style>
       .leftstr, .rightstr {
        float: left; /* Обтекание справа */ 
        width: 50%; /* Ширина текстового блока */ 
       }
       .rightstr {
        text-align: right; /* Выравнивание по правому краю */ 
       }
        .center {
        text-align: center; 
        width: 100%; /* Ширина текстового блока */ 

       }

    </style>
    <meta http-equiv="refresh" content="60">
{% endblock %}
{% block content %}
    <p><a href="/tasks/">К списку задач</a></p>
    <p><a href="/deleted_tasks/">К списку удалённых задач</a></p>
    <hr />
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
    </form>
    <hr />
    {# если только открыли #}
    {% if not not_finded and not finded_tasks %}
        {% if my_error %}
            {% for error in my_error %}
                <h2>{{error}}</h2><br />
            {% endfor %}
        <hr />
        {% endif %}
        
        {% if tasks %}
            <p>Открытые заявки</p>
                <ol>
                    {% for task in tasks %}
                        <li><a href="../task/one_time/{{task.id}}">{{task.id}};{{task.name}}</a></li>
                    {% endfor %}
                </ol>
        {% endif %}
        {% if regular_tasks %}
            <p>Повторяющиеся заявки</p>
                <ol>
                    {% for task in regular_tasks %}
                        <li><a href="../task/regular/{{task.id}}">{{task.id}};{{task.name}}</a></li>
                    {% endfor %}
                </ol>
        {% endif %}
        {% if closed_tasks %}
            <p>Закрытые заявки</p>
                <ol>
                    {% for task in closed_tasks %}
                        <li><a href="../task/one_time/{{task.id}}">{{task.id}};{{task.name}}</a></li>
                    {% endfor %}
                </ol>
        {% endif %}

        {% if confirmed_tasks %}
            <p>Подтверждённые заявки</p>
                <ol>
                    {% for task in confirmed_tasks %}
                        <li><a href="../task/one_time/{{task.id}}">{{task.id}};{{task.name}}</a></li>
                    {% endfor %}
                </ol>
        {% endif %}
    {% endif %}
    
    {# Если не найдена задача #}
    {% if not_finded and not finded_tasks %}
        <h1>Такой задачи не найдено, повторите поиск</h1>
    {% endif %}
    
    {# Если найдена задача #}
    {% if not not_finded and finded_tasks %}
        <ul>
            {% for task in finded_tasks %}
                <li><a href="/task/{{ task.in_link_type }}/{{task.id}}">{{task.id}};{{task.name}}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

{% if page_number >= 1 %}
    <a href="/all_task/{{ page_number|add:"-1" }}/">Пред. страница</a>
{% endif %}
{% if page_number < max_page_number %}
    <a href="/all_task/{{ page_number|add:"1" }}/">След. страница</a>
{% endif %}
{% endblock %}

todoes/templates/RUS/any_text.html
{% extends "todoes:RUS/base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1 style="text-align: center;">{{ message.name }}</h1>
<p>{{ message.text | safe }}</p>
<p style="text-align: right;"><i>{{ message.author.fio }}</i></p>
<p style="text-align: right;"><i>{{ message.timestamp }}</i></p>
{% endblock %}

todoes/templates/RUS/confirm_ticket.html
{% extends "RUS/base.html" %}
{% block title %}
    Подтвеждаем завершение задачи
{% endblock %}
{% block style %}
    <style>
       .leftstr, .rightstr {
        float: left; /* Обтекание справа */ 
        width: 50%; /* Ширина текстового блока */ 
       }
       .rightstr {
        text-align: right; /* Выравнивание по правому краю */ 
       }
      </style>
{% endblock %}
{% block content %}
    <p class="leftstr"><a href="/tasks/">К списку задач</a></p>
    <p class="rightstr">Привет, {{ fio.fio }}!</p>
     
    
    <br />
    <table border=0>
    <tr>
        <td>
            <table border=1>
            <tr><th colspan="2">Выбранная задача: {{task.name}}</th></tr>
                <td>Заказчик</td><td>{{task.client.fio}}</td></tr>
                <td>Категория</td><td>{{task.category}}</td></tr>
                <td>Исполнитель</td><td>{{task.category}}</td></tr>
                <td>Приоритет</td><td>{{task.priority}}</td></tr>
                <td>Дата создания</td><td>{{task.start_date}}</td></tr>
                <td>Предполагаемая дата завершения</td><td>{{task.due_date}}</td></tr>
                <td>Проблема со слов пользователя</td><td>{{task.pbu}}</td></tr>
            </table>
        </td>
        <td>
            <p>{{task.description|safe}}</p>
            <form action="" method="post">
                {% csrf_token %}
                <table border=1>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Подтвердить закрытие задачу" name="confirm_task" onclick="if (confirm('Уверены?')) {return true} else {return false};"/>
            </form>

{#            <table border=1>#}
{#                <tr><th colspan="2">Комментарии</th></tr>#}
{#                    {% for note in notes %}#}
{#                        <tr>#}
{#                            <form action="" method="post">#}
{#                         {% csrf_token %}#}
{#                        <td>{# {{note.id}}; #}
{#                            {{note.note|safe}}#}
{#                        </td>#}
{#                        <td>#}
{#                            <input type="hidden" name="num" value="{{note.id}}" />#}
{#                            <input type="submit" value="Удалить комментарий" name="del_comment" />#}
{#                        </td>#}
{#                            </form>#}
{#                    </tr>#}
{#                    {% endfor %}#}
{#            </table>#}

            {# Вывод таблицы с комментариями #}

            <table border=1>
                <tr>
                    <td>
                        Комментарии
                    </td>
                </tr>
                {% for note in notes %}
                    <tr>
                        <td style="padding: 0px 0px 0px {{note.indent_pix}}%;">
                            {# Текст комментария #}
                            {{note.note|safe}}<br />
                            <div class="author">
                                <i>
                                    {{note.timestamp}}
                                    {% if note.author %}
                                        {{note.author.fio}}
                                    {% endif %}
                                </i></div>
                        </td>
                    </tr>
                {% endfor %}
            </table>


        </td>
    </table>
    
{% comment %}
    class Task(models.Model):
        name = models.CharField(max_length=140)
        description = models.TextField()
        client = models.ForeignKey(Client)
        priority = models.PositiveSmallIntegerField()
        category = models.ForeignKey(Categories)
        start_date = models.DateTimeField()
        due_date = models.DateTimeField()
        done_date = models.DateTimeField(blank = True, null = True)
        worker = models.ForeignKey(Worker)
        resource = models.ForeignKey(Resource, blank = True, null = True)
        note = models.ManyToManyField(Note, related_name = "for_task",blank = True, null = True)
        file = models.ForeignKey(File, blank = True, null = True)
        percentage = models.PositiveSmallIntegerField()
        pbu = models.ForeignKey(ProblemByUser)
        pbw = models.ForeignKey(ProblemByWorker,blank = True, null = True)
        confirmed = models.NullBooleanField(blank = True, null = True)
        confirmed_date = models.DateTimeField(blank = True, null = True)
        def __unicode__(self):
            return u"\t".join((self.name,self.description,self.worker.fio,str(self.percentage)))
{% endcomment %}            



{% endblock %}

todoes/templates/RUS/logout.html
{% extends "RUS/base.html" %}
{% block title %}
Выход из системы

{% endblock %}
{% block content %}

Вы успешно вышли из системы
{% endblock %}

todoes/templates/RUS/new_ticket.html
{% extends "RUS/base.html" %}
{% block title %}
    Новый тикет
{% endblock %}
{% block style %}
    <script>
    </script>
    <style>
    </style>
{% endblock %}
{% block content %}
    {% if form.errors %}
    {#    {{form.errors}} #}
    {% endif %}
    <form action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table border=1>
            {{ form.as_table }}
        </table>
        <input type="hidden" name="due_date_request_reason" id="due_date_request_reason" value="" />
        <input type="submit">
    </form>
    <script>
        $.each($("td").find("ul.errorlist"),function(index,val){
            console.log($(val).css('background-color','red'))
        })
        {% if need_reason %}
            var old_date = $("#id_due_date").val();
            $("#id_due_date").on('change',function(){
                if ($("#id_due_date").val() != old_date)
                var a = prompt('Введите причину переноса даты выполнения','');
                $("#due_date_request_reason").val(a);
                return true;
                //console.log(a);
            })
        {% endif %}
    </script>
{% endblock %}

todoes/templates/RUS/password_change_done.html
{% extends "RUS/base.html" %}
{% block title %}Password Change Successful{% endblock %}
{% block content %}
    Your password has been changed successfully. Please re-login with your new credentials 
    <a href="/login/">login</a> or go back to the
    <a href="/">main page</a>.
{% endblock %}